---
- name: ensure the minio group is present
  group:
    name: "{{ dubzland_minio_service_group }}"
    state: present

- name: ensure the minio user is present
  user:
    name: "{{ dubzland_minio_service_user }}"
    group: "{{ dubzland_minio_service_group }}"
    system: yes

- name: ensure the minio data directory is present
  file:
    path: "{{ dubzland_minio_data_dir }}"
    state: directory
    owner: "{{ dubzland_minio_service_user }}"
    group: "{{ dubzland_minio_service_group }}"
    mode: 0700

- name: ensure the minio binary is present
  get_url:
    url: "{{ dubzland_minio_download_url }}"
    dest: /usr/local/bin/minio
    owner: root
    group: root
    mode: 0755

- name: ensure the minio environment file is present
  template:
    src: "etc/default/minio.j2"
    dest: "/etc/default/minio"
    owner: root
    group: root
    mode: 0644
  notify: restart minio

- name: ensure the systemd unit is present
  template:
    src: "etc/systemd/system/minio.service.j2"
    dest: "/etc/systemd/system/minio.service"
    owner: root
    group: root
    mode: 0755
  notify: reload systemd

- name: ensure minio is enabled
  service:
    name: minio
    enabled: True

- meta: flush_handlers

- name: ensure minio is running
  service:
    name: minio
    state: started
